### ISSUE TITLE
Next initialization steps

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/xradar#1]
@mgrover1 Thanks for setting this up.

What would be the next steps? Please extend this list.

- [x] release on PyPI
- [x] enable GitHub actions
  - [x] Doc building
  - [x] Publishing
  - [x] Running tests
- [x] add doc building infrastructure (including readthedocs)
- [x] fix rtd build (obviously installing from GitHub releases, version 999)
- [x] Covert root-folder `.rst` files to markdown
- [x] Covert the existing documentation `.rst` files to markdown where possible
- [x] link documentation to new docs.openradarscience.org subdomain
- [x] license entity (maybe openradar developers?)

**Comment by mgrover1** [comment]
I put together a 0.0.0 release here - just so we can reserve the namespace

**Comment by kmuehlbauer** [comment]
@mgrover1 It works now to create the correct version. But we would need to keep an eye on it.

**Comment by kmuehlbauer** [comment]
@magrover1 Could you elaborate how the bridge to RTD is closed. We might need to tweak this a bit to get the documentation build from the latest commit/tag instead of some source without the version.py as of now.

**Comment by kmuehlbauer** [comment]
@mgrover I think we've passed almost all initalization steps. How should we handle the license entity in "LICENSE"? Should we move to "openradar developers"?

**Comment by kmuehlbauer** [comment]
Örks, two times misspelled @mgrover1 in a row. :face_with_spiral_eyes:

**Comment by mgrover1** [comment]
> @mgrover1 I think we've passed almost all initalization steps. How should we handle the license entity in "LICENSE"? Should we move to "openradar developers"?

That sounds good!

**Comment by kmuehlbauer** [comment]
Done! :+1:
