### ISSUE TITLE
Make sure cfradial1 reader conforms to cfradial 1.4 standard

### ISSUE THREAD

**Issue by mgrover1** [openradar/xradar#107]
* xradar version: 0.2.0
* Python version: 3.11
* Operating System: MacOS

### Description

The current cfradial1 reader does not work with cfradial version 1.4 files, specifically with the name of the `sweep` variable

According to the [cradial 1.4 documentation](https://www.eol.ucar.edu/sites/default/files/files_live/private/CfRadialDoc.v1.4.20160801.pdf), this variable is named `sweep` and not `sweep_number` which is used in the current cfradial1 xradar reader.

### What I Did

```python
import xradar as xd

tree = xd.io.open_cfradial1_datatree(file)
```

which returned 
```python-traceback
ValueError: cannot rename 'sweep_number' because it is not a variable or coordinate in this dataset
```

**Comment by kmuehlbauer** [comment]
@mgrover1 Somehow this went under my radar. Can you share the file in question. According to the linked standard, `sweep_number` is a valid mandatory sweep variable (see 4.7 p. 22).

**Comment by mgrover1** [comment]
@kmuehlbauer - I think we can close this, I could not track down the file + you are right about `sweep_number` being a required variable! Sorry about that!!

**Comment by kmuehlbauer** [comment]
@mgrover1 No worries. The thing is I was getting errors mentioning `sweep_number` recently, too. It has to do with coord/non-coord. If I encounter again I'll create a new issue.
