### ISSUE TITLE
Add xradar team

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/xradar#130]
This is more an information issue. But we can start a discussion from it.

I've created an `xradar`-team in the `openradar`-org and have added @mgrover1, @zssherman and @kmuehlbauer to it. I've invited @egouden, @aladinor and @syedhamidali to join.

The team has currently `triage` status. But we can discuss to level up to `write` status, if everyone is OK with it.

We already acknowledge our contributors in several ways, but we should also try to give something back in terms of responsibility. Triaging issues and pullrequest beside active code contribution is also something which will help the xradar-project grow.

**Comment by mgrover1** [comment]
This sounds great @kmuehlbauer - should we have them respond to this issue to confirm they are willing to be reviewers of PRs?

**Comment by kmuehlbauer** [comment]
> This sounds great @kmuehlbauer - should we have them respond to this issue to confirm they are willing to be reviewers of PRs?

Yes, might be a good idea, if they respond here.

**Comment by zssherman** [comment]
@kmuehlbauer Also sounds good to me! Thanks!

**Comment by kmuehlbauer** [comment]
done, see -> https://github.com/orgs/openradar/teams/xradar
