### ISSUE TITLE
Deprecated ruff call in CI ?

### ISSUE THREAD

**Issue by wolfidan** [openradar/xradar#176]
* xradar version: 0.5.0
* Python version: -
* Operating System: -

### Description

CI of xradar uses ruff in the following way

     ruff .

But this leads to error

     error: `ruff <path>` has been removed. Use `ruff check <path>` instead.
     Error: Process completed with exit code 1.

### What I Did

Submitted a PR

**Comment by zssherman** [comment]
@wolfidan Thanks for the heads up! I can get a PR in to fix it.

**Comment by zssherman** [comment]
Max beat me to it, will be fixed in #177 !
