### ISSUE TITLE
Minimize CI

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/xradar#191]
Currently we've testing 

- unittests py310, py311 and py312 for numpy 1 and 2 -> 6 testruns
- notebooktests py310, py311 and py312 for numpy 1 and 2 -> 6 testruns

To minimize CI usage I'd suggest the following:

- unittests py310, py312 for numpy 1 and 2 -> 4 testruns
- notebook tests py312, numpy 2 -> 1 testrun

This might not really reduce overall runtime but we've cutted the CI time to roughly 40% without reducing much coverage. Thoughts?

**Comment by mgrover1** [comment]
This makes a lot of sense @kmuehlbauer - I like the idea of reducing the number of test runs here
