### ISSUE TITLE
API reference missing in the documentation

### ISSUE THREAD

**Issue by syedhamidali** [openradar/xradar#208]
* xradar version: 0.6.4
* Python version: N/A
* Operating System: N/A

I noticed there are some missing library references, for example, ``xradar.io.export.cfradial1.to_cfradial1`` in the Xradar documentation [Radar Data IO](https://docs.openradarscience.org/projects/xradar/en/stable/io.html), and also in the Section Navigations.

**Comment by kmuehlbauer** [comment]
Nice catch @syedhamidali. We should address this and the other issues and pr next week.

**Comment by kmuehlbauer** [comment]
resolved in #202
