### ISSUE TITLE
Port odim and cfradial2 writers from wradlib

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/xradar#37]
This might help people to get their data into ODIM_H5. 

The cfradial2 write might not have to be ported with all bits and pieces as we just can rely on datatree itself.

- [x] ODIM_H5 export #39

**Comment by mgrover1** [comment]
Agreed! I will not have time today, but I will have time these next few weeks to look at this.

**Comment by kmuehlbauer** [comment]
@mgrover1 I have a prototype almost finished for the odim part in my fork. I hope to submit during the weekend.

**Comment by kmuehlbauer** [comment]
Seems, that this is fixed. xradar's DataTree implementation should take care of writing proper CfRadial2.
