### ISSUE TITLE
Georeferencing follow-up issue 

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/xradar#38]
to not forget the items from #25: 

- [x] Move cartesian coordinate definition into model see https://github.com/openradar/xradar/pull/28#discussion_r981978559
- [ ] use model functionality to create Dataset
- [ ] docstring fixes
- [x] use site-coordinates (lat, lon, alt) to calculate final bin aeqd coordinates #87 
- [x] add spatial_ref to Dataset/DataArray on georeferencing #87 
- [ ] tbc

**Comment by mgrover1** [comment]
For georeferencing... @kmuehlbauer what would you think if we had an optional cartopy dependency? To deal with these projections?

**Comment by kmuehlbauer** [comment]
@mgrover1 Do you refer to map-making? Could you elaborate a bit more with regard to what functionality you have in mind?

**Comment by mgrover1** [comment]
I am thinking in terms of projecting data as well - see the MetPy functionality here https://unidata.github.io/MetPy/latest/examples/XArray_Projections.html

**Comment by kmuehlbauer** [comment]
Yes, I see, they use an accessor to get a cartopy crs object.

From my perspective we would just need to add the aeqd cartopy crs to Dataset/DataArray when creating xyz-coordinates if cartopy is available.

**Comment by mgrover1** [comment]
Yup! That makes sense!

**Comment by mgrover1** [comment]
Sorry for the delay here @kmuehlbauer ... prepping for our ARM/ASR meeting next week.

**Comment by kmuehlbauer** [comment]
No worries @mgrover1. It's great we are this far already.

**Comment by kmuehlbauer** [comment]
> From my perspective we would just need to add the aeqd cartopy crs to Dataset/DataArray when creating xyz-coordinates if cartopy is available.

@mgrover1 I've though about that the last days and tinkered a bit with `pyproj`. I've ended up with a workflow where we can use `pyproj` to:

- georeference the data using the derived latitude-dependend earth-radius
- write_crs (as `spatial_ref` - Variable)
- get_crs (retrieve `spatial_ref` or create on the fly if not available)

The would be able to wrap that into a `cartopy.crs.Projection` and use it for plotting with cartopy.

That would leave us with only `pyproj`/`proj` as additional dependencies. We could even make this optional. I'll see if I can workout a PR from that.

**Comment by kmuehlbauer** [comment]
@mgrover1 I've setup a PR with a minimal pyproj-based solution in #87.

**Comment by kmuehlbauer** [comment]
@mgrover1 We might close this issue and #25, as we have the basic workable georeferencing available now. WDYT?

**Comment by mgrover1** [comment]
Agreed! Let's do it.
