### ISSUE TITLE
Site-coordinates at Sweep-Level

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/xradar#48]
In CfRadial2-standard the sweep-groups do not contain the site-coordinates (`latitude`/`longitude`/`altitude`). Although that makes perfectly sense when reading the whole DataTree, it might be not as perfect for the single-sweep reading via `xr.open_dataset`. The site-coordinates (at least `latitude` and `altitude`) might be used for georeferencing.

I'd suggest to enable the xarray-backends to add the site-coordinates to the returned Dataset. We have at least the following options:

- return site-coords per default in any case
- return site-coords per kwarg-request per default
- return site-coords per kwarg-request not per default
- ?

Thoughts?

**Comment by mgrover1** [comment]
I like the idea of keeping that at the root level... we can add an attribute perhaps? But keeping at the root dataset level makes sense

**Comment by kmuehlbauer** [comment]
@mgrover1 Yes, they should definitely stay at the root group. And they should not show up in sweep groups inside DataTree.

But it would be great if they could show up when single sweeps are read via `xr.open_dataset`.

I'll create a PR with a proposal.
