### ISSUE TITLE
Move to pure pyproject.toml builds

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/xradar#66]
@mgrover1 I'm thinking about adopting pure `pyproject.toml` based builds to get rid of `setup.py`/`setup.cfg`. This would include moving linting to `ruff`. WDYT?

**Comment by mgrover1** [comment]
Yes - I think this would make sense/adopting ruff here would be a good choice.

**Comment by mgrover1** [comment]
I really want to learn how to migrate as well...

**Comment by kmuehlbauer** [comment]
I did it recently on a small project, but xradar would be the first with more things involved. So still learning here too :-)
